TOOLS = [
    {
        "name": "Merge PDF",
        "description": "Combine multiple PDF files into one single document in the exact order you want.",
        "url": "/merge-pdf",
        "icon": "/assets/icons/merge-pdf.svg",
        "color": "#eef7ff",
        "category": ["Organize PDF"],
    },
    {
        "name": "Split PDF",
        "description": "Extract specific pages or separate your PDF into multiple individual documents.",
        "url": "/split-pdf",
        "icon": "/assets/icons/split-pdf.svg",
        "color": "#fff1f1",
        "category": ["Organize PDF"],
    },
    {
        "name": "Compress PDF",
        "description": "Reduce the size of your PDF while maintaining the highest possible file quality.",
        "url": "/compress-pdf",
        "icon": "/assets/icons/compress-pdf.svg",
        "color": "#fffdf0",
        "category": ["Optimize PDF"],
    },
    {
        "name": "PDF to Excel",
        "description": "Convert your PDF data into editable Excel spreadsheets with high cell accuracy.",
        "url": "/pdf-to-excel",
        "icon": "/assets/icons/pdf-to-excel.svg",
        "color": "#DA000029",
        "category": ["Convert PDF"],
    },
    {
        "name": "Excel to PDF",
        "description": "Transform Excel workbooks into professional PDF documents for easy distribution.",
        "url": "/excel-to-pdf",
        "icon": "/assets/icons/excel-to-pdf.svg",
        "color": "#8FBC5D3D",
        "category": ["Convert PDF"],
    },
    {
        "name": "PDF to JPG",
        "description": "Convert every PDF page into a high-quality JPG image for visual use cases.",
        "url": "/pdf-to-jpg",
        "icon": "/assets/icons/pdf-to-jpg.svg",
        "color": "#D2DAED",
        "category": ["Convert PDF"],
    },
    {
        "name": "JPG to PDF",
        "description": "Combine JPG, PNG, and TIFF images into one high-quality PDF file in seconds.",
        "url": "/jpg-to-pdf",
        "icon": "/assets/icons/jpg-to-pdf.svg",
        "color": "#04CDD429",
        "category": ["Convert PDF"],
    },
    {
        "name": "PDF to Word",
        "description": "Convert your PDF files into editable Word documents while preserving formatting.",
        "url": "/pdf-to-word",
        "icon": "/assets/icons/pdf-to-word.svg",
        "color": "#4676ED33",
        "category": ["Convert PDF"],
    },
    {
        "name": "Word to PDF",
        "description": "Easily convert Word documents into professional PDF files with perfect layout.",
        "url": "/word-to-pdf",
        "icon": "/assets/icons/word-to-pdf.svg",
        "color": "#f0f7ff",
        "category": ["Convert PDF"],
    },
    {
        "name": "PPT to PDF",
        "description": "Convert PowerPoint presentations into high-quality PDF files for easy sharing.",
        "url": "/ppt-to-pdf",
        "icon": "/assets/icons/ppt-to-pdf.svg",
        "color": "#fbf3ff",
        "category": ["Convert PDF"],
    },
    {
        "name": "Sign PDF",
        "description": "Add legally binding signatures to your PDF documents quickly and securely.",
        "url": "/sign-pdf",
        "icon": "/assets/icons/sign-pdf.svg",
        "color": "#eefdfa",
        "category": ["PDF Security"],
    },
    {
        "name": "Watermark",
        "description": "Stamp customized text or images onto your PDF pages for professional branding.",
        "url": "/watermark",
        "icon": "/assets/icons/watermark.svg",
        "color": "#fffbf0",
        "category": ["PDF Intelligence"],
    },
    {
        "name": "Protect PDF",
        "description": "Secure your PDF documents with strong encryption and custom access passwords.",
        "url": "/protect-pdf",
        "icon": "/assets/icons/protect-pdf.svg",
        "color": "#f3faf4",
        "category": ["PDF Security"],
    },
    {
        "name": "Unlock PDF",
        "description": "Remove password protection and security restrictions from your PDF documents.",
        "url": "/unlock-pdf",
        "icon": "/assets/icons/unlock-pdf.svg",
        "color": "#fdf2f8",
        "category": ["PDF Security"],
    },
    {
        "name": "AI Summarizer",
        "description": "Summarize complex PDF documents using advanced AI to extract key insights.",
        "url": "/ai-summerizer",
        "icon": "/assets/icons/ai-summerizer.svg",
        "color": "#f5f3ff",
        "category": ["PDF Intelligence"],
    },
    {
        "name": "Rotate PDF",
        "description": "Rotate your PDF pages to the correct orientation for professional viewing.",
        "url": "/rotate-pdf",
        "icon": "/assets/icons/rotate-pdf.svg",
        "color": "#FDC04B3D",
        "category": ["Optimize PDF"],
    },
    {
        "name": "Organize PDF",
        "description": "Rearrange, delete, or add new pages to your PDF documents with easy tools.",
        "url": "/organize-pdf",
        "icon": "/assets/icons/organize-pdf.svg",
        "color": "#EAD2CA",
        "category": ["Organize PDF"],
    },
    {
        "name": "Scan PDF",
        "description": "Scan physical documents and convert them into digital PDF files instantly.",
        "url": "/scan-pdf",
        "icon": "/assets/icons/scan-pdf.svg",
        "color": "#CACACA",
        "category": ["Optimize PDF"],
    },
    {
        "name": "OCR PDF",
        "description": "Recognize and extract text from scanned PDF images using optical technology.",
        "url": "/ocr-pdf",
        "icon": "/assets/icons/ocr-pdf.svg",
        "color": "#8FBC5D66",
        "category": ["PDF Intelligence", "Edit PDF"],
    },
    {
        "name": "Crop PDF",
        "description": "Trim unwanted margins or specific areas from your PDF pages for better focus.",
        "url": "/crop-pdf",
        "icon": "/assets/icons/crop-pdf.svg",
        "color": "#D6EFFF",
        "category": ["Optimize PDF", "Edit PDF"],
    },
    {
        "name": "Edit PDF",
        "description": "Modify text, images, and shapes directly within your PDF document easily.",
        "url": "/edit-pdf",
        "icon": "/assets/icons/edit-pdf.svg",
        "color": "#ECEBCA",
        "category": ["Optimize PDF", "Edit PDF"],
    },
    {
        "name": "Compare PDF",
        "description": "Identify differences between two PDF versions with side-by-side comparison.",
        "url": "/compare-pdf",
        "icon": "/assets/icons/compare-pdf.svg",
        "color": "#E4D6E4",
        "category": ["Optimize PDF"],
    },
    {
        "name": "Redact PDF",
        "description": "Permanently remove sensitive information and private data from your PDFs.",
        "url": "/redact-pdf",
        "icon": "/assets/icons/redact-pdf.svg",
        "color": "#EFE9C7",
        "category": ["PDF Security"],
    },
    {
        "name": "Page Numbers",
        "description": "Add professional page numbering and custom header/footer layouts to PDFs.",
        "url": "/page-number",
        "icon": "/assets/icons/page-number.svg",
        "color": "#edf2f7",
        "category": ["Organize PDF", "Edit PDF"],
    },
]
